runtime: nodejs18

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 2

env_variables:
  DB_HOST: YOUR_CLOUD_SQL_HOST
  DB_USER: YOUR_DB_USER
  DB_PASSWORD: YOUR_DB_PASSWORD
  DB_NAME: YOUR_DATABASE_NAME
  JWT_SECRET: YOUR_SECRET_KEY